run:
  plot_every_n_batches: 1000
  n_epochs: 80
  batchsize: 1
  num_workers: 0
  learning_rate_decay: 0.25
  learning_rate_decay_step_size: 750
  compute_validation_loss: true
  compute_validation_loss_every_n_epochs: 10
  custom_init: false
  minibatch_epoch_loss: true
  evaluate_testset: false
  warm_start: false
  save_model: true
  save_metadata: true
  save_model_every_n_epoch: 5
  save_params_hist_every_n_epoch: 100
  optimizer_type: adam
  optimizer_kwargs:
    lr: 3.0e-05
loss:
  loss_components:
  - L2Loss
  learn_scaling: true
  L1Loss_kwargs:
    exclude_terrain: true
    loss_factor_init: -0.5
  L2Loss_kwargs:
    exclude_terrain: true
    loss_factor_init: -0.5
  L4Loss_kwargs:
    exclude_terrain: true
    loss_factor_init: 1.5
  LPLoss_kwargs:
    exclude_terrain: true
    p: 1.7
    loss_factor_init: 0.0
  ScaledLoss_kwargs:
    exclude_terrain: true
    no_scaling: true
    max_scale: 4
    norm_threshold: 0.5
    loss_factor_init: 0.0
  DivergenceFreeLoss_kwargs:
    exclude_terrain: true
    loss_type: L1
    loss_factor_init: -1.5
  VelocityGradientLoss_kwargs:
    exclude_terrain: true
    loss_type: L1
    loss_factor_init: -1.5
  GaussianLogLikelihoodLoss_kwargs:
    exclude_terrain: true
    uncertainty_loss_eps: 1e-8
    loss_factor_init: 0.0
  KLDivLoss_kwargs:
    loss_factor_init: 0.0
  log_loss_components: true
  loss_weighting_fn: 0
  loss_weighting_clamp: true
  auto_channel_scaling: true
  eps_scaling: 1
  eps_scheduling_mode: decay
  eps_scheduling_kwargs:
    gamma: 0.9935
    step_size: 10
data:
  trainset_name: /media/phantom/Volume/WindSeer Data/download (2)/658323/train.hdf5
  validationset_name: /media/phantom/Volume/WindSeer Data/download (2)/658323/validation_resampled_32.hdf5
  testset_name: data/test.hdf5
  input_channels:
  - terrain
  - ux
  - uy
  label_channels:
  - ux
  - uy
  - uz
  augmentation: true
  augmentation_mode: 1
  augmentation_kwargs:
    subsampling: true
    rotating: true
  input_mode: 5
  stride_hor: 1
  stride_vert: 1
  ux_scaling: 1.0
  uy_scaling: 1.0
  uz_scaling: 1.0
  turb_scaling: 1.0
  p_scaling: 1.0
  epsilon_scaling: 1.0
  nut_scaling: 1.0
  terrain_scaling: 1.0
  autoscale: false
  additive_gaussian_noise: true
  max_gaussian_noise_std: 0.1
  n_turb_fields: 0
  max_normalized_turb_scale: 0.0
  max_normalized_bias_scale: 0.1
  only_z_velocity_bias: false
  max_fraction_of_sparse_data: 0.1
  min_fraction_of_sparse_data: 0.001
  trajectory_min_length: 3
  trajectory_max_length: 60
  trajectory_min_segment_length: 5
  trajectory_max_segment_length: 20
  trajectory_step_size: 1.0
  trajectory_max_iter: 50
  trajectory_start_weighting_mode: 0
  trajectory_length_short_focus: false
  input_smoothing: true
  input_smoothing_interpolation: false
  input_smoothing_interpolation_linear: true
model:
  name_prefix: cpu_sparse_full_eth
  model_type: ModelEDNN3D
  model_args:
    n_x: 32
    n_y: 32
    n_z: 32
    n_downsample_layers: 4
    n_first_conv_channels: 8
    channel_multiplier: 2
    filter_kernel_size: 3
    interpolation_mode: nearest
    align_corners: false
    skipping: true
    use_terrain_mask: true
    pooling_method: striding
    use_fc_layers: false
    fc_scaling: 8
    use_mapping_layer: false
    potential_flow: false
    activation_type: LeakyReLU
    activation_args:
      negative_slope: 0.1
    verbose: true
    submodel_type: ModelEDNN3D
    vae: false
    use_uz_in: false
    use_sparse_mask: true
    use_sparse_convolution: false
    predict_uncertainty: false
    uncertainty_train_mode: alternating
    logvar_scaling: 10
    n_stacked: 3
    pass_full_output: false
    submodel_terrain_mask: false
    use_turbulence: false
